### ISSUE TITLE
Do we need to use the same APP_KEY in development and production

### ISSUE THREAD

**Issue by kornatzky** [beyondcode/laravel-credentials#13]
It seems that if you change the APP_KEY you can no longer retrieve the credentials. Is this the case?

When you do:

    php artisan edit:credentials

You get the error:

  In Encrypter.php line 195:
                       
  The MAC is invalid.

**Comment by mpociot** [comment]
Yes, the default key that is being used for encryption is the APP_KEY. You can change it in the config file: https://github.com/beyondcode/laravel-credentials/blob/master/config/credentials.php#L14
