### ISSUE TITLE
artisan credentials:edit does not work on Windows

### ISSUE THREAD

**Issue by miklcct** [beyondcode/laravel-credentials#15]
When I try to run `php artisan credentials:edit`, it throws a `RuntimeException` with message `TTY mode is not supported on Windows platform.`

**Comment by ghost** [comment]
Same issue.

**Comment by ab0ris** [comment]
I assume it's all about `src/EditCredentialsCommand.php:46`, where it should check for platform and skip if Windows:
```
if (!(stripos(PHP_OS, 'WIN') === 0 || PHP_OS_FAMILY === "Windows")) {
        $process->setTty(true);
}
```
Or simply handle the exception.

Unfortunately, I don't have Windows to verify this code.
