### ISSUE TITLE
How does this package secure access to encrypted credentials?

### ISSUE THREAD

**Issue by connecteev** [beyondcode/laravel-credentials#21]
Say I have secret credentials for production, that I don't want to give anyone access to. If I use this package and store my encrypted credentials in version control, and then give a freelancer access to my git repo so that they can work on it, doesn't that mean they could now access my production credentials also?

How does this package solve this problem, of not allowing other developers from accessing sensitive data?

**Comment by ejunker** [comment]
You could use a different key for production and make sure that the key is not checked into your git repo.

**Comment by connecteev** [comment]
@ejunker I get that, but then why use this package? Sorry if I am not understanding the utility!

**Comment by ejunker** [comment]
If you want to check your configuration into git but not expose the credentials then this package is useful. You could also just not put any of your credentials in git and set everything as an environment variable on your server or have a separate .env file that you don't check into git but that isn't always convenient. With this package, you just have to figure out how to securely set the key. You could even use something like AWS Secrets Manager to store the encryption key.

**Comment by connecteev** [comment]
@ejunker I don't get it.

> With this package, you just have to figure out how to securely set the key.

Won't the key also need to be stored in git? If so, that defeats the purpose of the package being secure. If it won't be stored in git, then how does the laravel app read the env variables?

**Comment by ejunker** [comment]
No, the encryption key should not be stored in git. By default, it uses Laravel's APP_KEY which should not be stored in git but rather somehow set on the server. I think if you are using Laravel Forge, it has a way to set environment variables or you can set environment variables in your apache config if you are using apache. I ended up writing an artisan command to pull the key from AWS Secrets Manager and inject it into my .env file. This article explains some of the ways to set an environment variable on the server https://dev.to/enygma/keeping-credentials-secure-in-php-1mgo

**Comment by connecteev** [comment]
@ejunker thanks for the clarification...this is helpful.
