### ISSUE TITLE
Laravel 6 BindingResolutionException when using credentials helper in config

### ISSUE THREAD

**Issue by ravellodev** [beyondcode/laravel-credentials#22]
This only seems to happen with Laravel 6 when attempting to use the credentials helper in a config file. I've tried on an upgraded 5.8->6.2.0 as well as a fresh 6.2.0 installation with the same results.

When trying to run an artisan command as a test I receive the error below. 

php artisan --version

In Container.php line 806
Target class [encrypter] does not exist.

In Container line 804
Class encrypter does not exist

After a little digging it seems that "Illuminate\Contracts\Encryption\Encrypter" hasn't been bound yet for the dependency in the constructor for the Credentials class. 

Laravel then throws a 

Illuminate\Contracts\Container\BindingResolutionException

**Comment by prafullguptaaus** [comment]
I'm facing the same issue while using this library with laravel 6.5.*.

**Comment by prafullguptaaus** [comment]
Is there any solution for this?

**Comment by ravellodev** [comment]
It looks like a simple change to helpers.php would do the trick

On line 23

Change 

} catch (ReflectionException $e) {

to

} catch (ReflectionException | BindingResolutionException $e) {

To test that out I ended up forking this package and it works fine

**Comment by prafullguptaaus** [comment]
Thanks. It worked for me as well.
