### ISSUE TITLE
decryption not working at config/database.php

### ISSUE THREAD

**Issue by lifetimesms** [beyondcode/laravel-credentials#35]
its not working at config/database.php 
Please suggest how to call in config/database.php .

it works fine in tinker / controller .

**Comment by hudacse6** [comment]
send me your Skype I,ll sent you the solution over there, thanks

**Comment by lifetimesms** [comment]
Skype : myeishvar

**Comment by amarcovich** [comment]
Same issue. ¿Anyone help me please?
