### ISSUE TITLE
Support php 8.0.8

### ISSUE THREAD

**Issue by Widres8** [beyondcode/laravel-credentials#43]
[InvalidArgumentException]
  Package beyondcode/laravel-credentials has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
  :
    - beyondcode/laravel-credentials requires php ^7.1 which does not match your installed version 8.0.8.
    - beyondcode/laravel-credentials requires illuminate/encryption 5.6.*|5.7.*|5.8.*|^6.0|^7.0|^8.0 but it is not present.

**Comment by mdtaiyabhesabe** [comment]
[InvalidArgumentException]
Package beyondcode/laravel-credentials has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version:
- beyondcode/laravel-credentials requires php ^7.1 which does not match your installed version 8.1.6.

**Comment by cyberlightdev** [comment]
I know it's an older issue and this is a workaround, but if you're wanting to use PHP 8/8.1 and or Laravel 9, my PR #44 can be used directly. Instructions are in my comment on that PR.
