### ISSUE TITLE
The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key length

### ISSUE THREAD

**Issue by kornatzky** [beyondcode/laravel-credentials#8]
After installing the package in a Laravel 5.6 project.
Doing:
php artisan vendor:publish --provider="BeyondCode\Credentials\CredentialsServiceProvider" --tag="config"
Leaving the defaults as is.

App Key was set by:
php artisan key:generate

Also I did:
php artisan config:clear 
php artisan config:cache

Then running:
php artisan credentials:edit

I get:

   RuntimeException  : The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

  at /home/johndoe/server/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:43
    39|         if (static::supported($key, $cipher)) {
    40|             $this->key = $key;
    41|             $this->cipher = $cipher;
    42|         } else {
  > 43|             throw new RuntimeException('The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.');
    44|         }
    45|     }
    46| 
    47|     /**

  Exception trace:

  1   Illuminate\Encryption\Encrypter::__construct("", "AES-256-CBC")
       /home/johndoe/server/vendor/beyondcode/laravel-credentials/src/CredentialsServiceProvider.php:54

  2   BeyondCode\Credentials\CredentialsServiceProvider::BeyondCode\Credentials\{closure}(Object(Illuminate\Foundation\Application), [])
       /home/johndoe/server/vendor/laravel/framework/src/Illuminate/Container/Container.php:764

  Please use the argument -v to see more details.

**Comment by leMaur** [comment]
Hi @kornatzky,
try in a different order:

```
// Clear your cache
$ php artisan config:clear

// Edit your config
$ php artisan credentials:edit

// Cache it
$ php artisan config:cache
```

**Comment by kornatzky** [comment]
Works. Thanks Saw this only now. Somehow the notification did not reach me.
